// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator for NON-COMMERCIAL USE
// Generator: RgenTemplate (internal)
// Generation date: 2014-06-15 08:57
// Generated by: GTS-DEV\Pranolo
//-------------------------------------------------------
namespace Templates
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.6.0")]
    [Kodeo.Reegenerator.Generators.TemplateDisplayAttribute(DisplayName="NotifyProperty", Description="NotifyPropertyChanged Code Generator", HideInDialog=false)]
    public partial class NotifyProperty : RgenLib.TaggedCodeRenderer
    {
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="output">The instance where the rendered code will be written to.</param>
        ///<param name="className"></param>
        ///<param name="IncludeNPC"></param>
        public virtual void GenFunctions(System.IO.StringWriter output, String className, Boolean IncludeNPC)
        {
            output.Write("\t");
 if (IncludeNPC) { 
            output.Write(" \r\n\t\tpublic event System.ComponentModel.PropertyChangedEventHandler PropertyChang" +
                    "ed;\r\n\t");
} 
            output.Write("\r\n\r\n    void ");
            output.Write( INotifierFullName );
            output.Write(".Notify(string propertyName) {  \r\n\t\tif (PropertyChanged != null) {\r\n            P" +
                    "ropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(property" +
                    "Name));\r\n        }\r\n    }");
            output.WriteLine();
        }
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        public virtual void Test()
        {
            this.Output.WriteLine();
        }
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="output">The instance where the rendered code will be written to.</param>
        ///<param name="propName"></param>
        ///<param name="propType"></param>
        ///<param name="existingComment"></param>
        ///<param name="attributes"></param>
        ///<param name="interfaceImpl"></param>
        public virtual void GenProperty(System.IO.StringWriter output, String propName, String propType, String existingComment, String attributes, String interfaceImpl)
        {
            output.Write("    private ");
            output.Write( propType );
            output.Write(" _");
            output.Write( propName );
            output.Write("; \r\n\t");
            output.Write( existingComment );
            output.Write("\r\n\t");
            output.Write( attributes 	);
            output.Write("\r\n\tpublic ");
            output.Write( propType );
            output.Write(" ");
            output.Write( propName );
            output.Write(" {\r\n        get {\r\n            return _");
            output.Write( propName );
            output.Write(";\r\n        }\r\n        set {\r\n            ");
 //Left empty to be filled by Generated code
            output.Write("\r\n        }\r\n    }");
            output.WriteLine();
        }
    }
}
