// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator for NON-COMMERCIAL USE
// Generator: RgenTemplate (internal)
// Generation date: 2014-06-14 08:41
// Generated by: GTS-DEV\Pranolo
//-------------------------------------------------------
namespace Templates
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.6.0")]
    [Kodeo.Reegenerator.Generators.TemplateDisplayAttribute(DisplayName="NotifyProperty", Description="NotifyProperty", HideInDialog=false)]
    public partial class NotifyProperty : Kodeo.Reegenerator.Generators.CodeRenderer
    {
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<returns></returns>
        public override Kodeo.Reegenerator.Generators.RenderResults Render()
        {
            this.Output.Write("// -------------------------------------------------------\r\n// Automatically gene" +
                    "rated with Kodeo\'s Reegenerator\r\n// Generator: NotifyProperty\r\n// Generation dat" +
                    "e: ");
            this.Output.Write( System.DateTime.Now.ToString("yyyy-MM-dd hh:mm") );
            this.Output.Write("\r\n// Generated by: ");
            this.Output.Write( System.Security.Principal.WindowsIdentity.GetCurrent().Name );
            this.Output.Write("\r\n// -------------------------------------------------------\r\n\r\n");
 
            this.Output.WriteLine();
            return new Kodeo.Reegenerator.Generators.RenderResults(this.Output.ToString());
        }
    }
}
